[package]
name = "os_pipe"
version = "0.1.1"
authors = ["Jack O'Connor"]
description = "an adaptation of the OS pipe code from stdlib as a standalone library"
repository = "https://github.com/oconnor663/os_pipe.rs"
license = "MIT"

[dependencies]
nix = ">=0.7.0"
