[package]
name = "os_pipe"
version = "0.6.1"
authors = ["Jack O'Connor"]
description = "a cross-platform library for opening OS pipes"
repository = "https://github.com/oconnor663/os_pipe.rs"
documentation = "https://docs.rs/os_pipe"
license = "MIT"

[target.'cfg(not(windows))'.dependencies]
nix = "0.10.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["handleapi", "namedpipeapi", "processenv", "winbase"] }
