[package]
name = "os_pipe"
version = "0.1.1"
authors = ["Jack O'Connor"]
description = "an adaptation of the OS pipe code from stdlib as a standalone library"
repository = "https://github.com/oconnor663/os_pipe.rs"
license = "MIT"

[target.'cfg(not(windows))'.dependencies]
nix = ">=0.7.0"

[target.'cfg(windows)'.dependencies]
winapi = ">=0.2.8"
kernel32-sys = ">=0.2.2"
