[package]
name = "os_pipe"
version = "0.2.1"
authors = ["Jack O'Connor"]
description = "a cross-platform library for opening OS pipes"
repository = "https://github.com/oconnor663/os_pipe.rs"
documentation = "https://docs.rs/os_pipe/0.2.0/os_pipe"
license = "MIT"

[target.'cfg(not(windows))'.dependencies]
nix = "^0.7.0"

[target.'cfg(windows)'.dependencies]
winapi = "^0.2.8"
kernel32-sys = "^0.2.2"
