[package]
name = "os_pipe"
version = "0.1.0"
authors = ["Jack O'Connor"]
description = "an adaptation of the OS pipe code from stdlib as a standalone library"
repository = "https://github.com/oconnor663/os_pipe.rs"
license = "MIT"

[dependencies]
libc = "0.2.*"
lazy_static = "0.2.*"
